added de_de
DimensionalDevelopment/DimDoors pull request #190
Opened 2021-03-01 00:59 UTC by Pankraz01

completely added translation of de_de (German)

2021-03-01 01:43 UTC, BoogieMonster1O1 commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "entity.dimdoors.monolith": "Monolith",
You can remove everything above `"entity.dimdoors.monolith": "Monolith",`
We dont use those translations anymore

2021-03-01 02:00 UTC, CreepyCre requested changes
Suggested some changes here and there to fit the lore better. Take care to be consistent with naming as well.

Pretty good translation in general though.

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "block.dimdoors.cyan_fabric": "Cyan Alternative Struktur",
Cyan -> Türkise
fits mojangs color naming scheme better. See https://minecraft-de.gamepedia.com/Wolle for example.

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "block.dimdoors.cyan_ancient_fabric": "Cyan Alternative Uralte Struktur",
Cyan -> Türkise
fits mojangs color naming scheme better. See https://minecraft-de.gamepedia.com/Wolle for example.

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "block.dimdoors.black_fabric": "Struktur der Realität",
`Struktur` doesn't really seem to fit the theme. Fabric is more akin to a bunch of entangled thread. (see world thread)
Something like `Gewebe`/ `Geflecht` might work better. So in its entirety it might be `Realitätsgeflecht`.

Might want to check with Codebracker on the symbolizism though.

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "item.dimdoors.rift_signature": "Riss Signatur",
`Rift` is actually a German word as well (https://www.duden.de/rechtschreibung/Rift). Debatable which sounds better, just resolve this comment if you think `Riss` is fine.

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "item.dimdoors.rift_signature.bound.info": "Führt zu (%d, %d, %d) bei Dimension #%d",
`bei` -> `in`

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "dimdoors.general.depthSpreadFactor": "Depth Spread Factor",
missing translation

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "item.dimdoors.iron_dimensional_door.info": "Auf dem Block unter einem Riss platzieren, \\num den Riss zu aktivieren, oder an einer anderen Stelle platzieren, \\num eine Pocket-Dimension zu erzeuge
``Pocket`` -> ``Taschendimension``/ ``Taschenuniversum``

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "dimdoors.advancement.escape_limbo.desc": "Entfliehe Limbo"
``Entfliehe`` -> ``Entkomme``
more commonly used

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "dimdoors.advancement.limbo": "Verfall",
``Limbo`` is the name of the dimension and really shouldn't be translated.

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "dimdoors.advancement.dungeon": "Dungeons",
Should be ``Verlies``, though``Dungeons`` might be more intuitive even though it isn't really a German word.

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "dimdoors.linkProperties.oneWay": "Eine Möglichkeit: %s",
``one way`` refers to the direction of travel. Sould probably be translated as ``Eine Richtung``.

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "dimdoors.config.screen.reload": "Konfig neu laden",
``Konfig`` -> ``Konfiguration``/ ``Einstellungen``

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "dimdoors.graphics.riftJitter": "Rissflackern",
``jitter`` is more akin to ``zittern``

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "item.dimdoors.dimensional_eraser": "Dimensionslöscher",
Pretty certain the concept is one of an actual eraser, so it should be ``Dimensionsradierer`` (or ``Dimensionaler Radierer`` if you want to make clear that it doesn't act upon dimensions, since that seems implied by the first suggestion)

2021-03-01 02:00 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "block.dimdoors.black_ancient_fabric": "Uralte Struktur",
``uralt`` -> ``antik``?
up to discussion, may sound better

2021-03-01 14:03 UTC, Pankraz01 commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "item.dimdoors.rift_signature": "Riss Signatur",
`Spalt` is also a good german translation for Rift

2021-03-01 14:05 UTC, Pankraz01 commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "item.dimdoors.iron_dimensional_door.info": "Auf dem Block unter einem Riss platzieren, \\num den Riss zu aktivieren, oder an einer anderen Stelle platzieren, \\num eine Pocket-Dimension zu erzeuge
I used Pocketdimension as the Word itself, because it is a major thing in DimDoors it should not be translatet to `Tasche`

2021-03-01 14:07 UTC, Pankraz01 commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "dimdoors.advancement.limbo": "Verfall",
`Limbo` is always translated as Limbo.
`Verfall` is the german translation of `Decay`.
![grafik](https://user-images.githubusercontent.com/19345513/109508203-e2e55080-7a9f-11eb-8b94-8a49e62fa245.png)

2021-03-01 14:09 UTC, Pankraz01 commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "dimdoors.config.screen.reload": "Konfig neu laden",
`Config` = `Configuration` -> `Konfig` = `Konfiguration`
`Settings` = `Einstellungen`

2021-03-01 14:12 UTC, Pankraz01 commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "block.dimdoors.black_ancient_fabric": "Uralte Struktur",
ancient -> `uralt`

2021-03-01 14:20 UTC, Pankraz01 commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "block.dimdoors.black_fabric": "Struktur der Realität",
Should i translate Fabric as `Geflecht` in general, or just that one?

2021-03-27 14:50 UTC, CreepyCre commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "block.dimdoors.black_fabric": "Struktur der Realität",
Unresolved since you didn't adress the requested changes. I you want to discuss which sounds better you can call me.

2021-03-31 13:25 UTC, Pankraz01 commented on src/main/resources/assets/dimdoors/lang/de_de.json
> +  "block.dimdoors.black_fabric": "Struktur der Realität",
![grafik](https://user-images.githubusercontent.com/19345513/113151346-45fc0b80-9235-11eb-9c56-c3a870a6f563.png)

2021-07-26 08:42 UTC, Waterpicker commented
What's the status on this one?

2023-08-02 07:54 UTC, Waterpicker commented
Two year poke I guess. Is this stale now?

2024-04-23 09:53 UTC, Yobrocharlie commented
this shit is more stale then a fucking isreal joke.

2025-12-19 20:12 UTC, closed without merging