we are all stable:tm:
DimensionalDevelopment/DimDoors pull request #193
Opened 2021-04-02 06:25 UTC by hYdos

2021-04-02 06:57 UTC, BoogieMonster1O1 requested changes
this should only be applied in dev

2021-04-02 10:52 UTC, hYdos commented
players dont like dealing with that screen either. it takes up loading time and is a pain

2021-04-02 11:00 UTC, hYdos commented
also yes now have working fluids
![image](https://user-images.githubusercontent.com/25501603/113410314-7939c880-93f6-11eb-8386-bec14e290e62.png)

2021-04-02 11:07 UTC, BoogieMonster1O1 commented on src/main/java/org/dimdev/dimdoors/mixin/EntityMixin.java
> +public abstract class EntityMixin {
no

2021-04-02 11:08 UTC, BoogieMonster1O1 commented
the warning is important, this is 1.17 and you can never be too careful

2021-04-02 11:08 UTC, BoogieMonster1O1 commented
plus there's mods that yeet it
nothing truly invasive goes in dimdoors

2021-04-21 08:14 UTC, Waterpicker commented
Since this was a general bad idea. Closing

2021-04-21 08:14 UTC, closed without merging